// Enhanced Plant Species Database - 47 House Plant Species
export const plantSpecies = [
  {
    id: 1,
    name: 'African Violet',
    scientificName: 'Saintpaulia ionantha',
    kaggleId: 'african_violet',
    family: 'Gesneriaceae',
    type: 'Flowering Houseplant',
    care: 'Moderate',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Compact flowering plant with velvety leaves and colorful blooms.',
    benefits: ['Beautiful flowers', 'Compact size', 'Air purification'],
    commonIssues: ['Crown rot', 'Leaf spot', 'Aphids'],
    tips: ['Water from bottom', 'Avoid cold water', 'High humidity'],
    features: ['velvety leaves', 'small flowers', 'rosette form'],
    colors: ['purple', 'pink', 'white'],
    season: 'Year-round blooming'
  },
  {
    id: 2,
    name: 'Aloe Vera',
    scientificName: 'Aloe barbadensis',
    kaggleId: 'aloe_vera',
    family: 'Asphodelaceae',
    type: 'Succulent',
    care: 'Easy',
    sunlight: 'Bright Direct',
    water: 'Low',
    soil: 'Sandy/Well-drained',
    description: 'Medicinal succulent plant with thick, fleshy leaves containing healing gel.',
    benefits: ['Medicinal properties', 'Air purification', 'Low maintenance'],
    commonIssues: ['Root rot', 'Overwatering', 'Sunburn'],
    tips: ['Water deeply but infrequently', 'Use well-draining soil', 'Harvest gel carefully'],
    features: ['thick fleshy leaves', 'serrated edges', 'rosette pattern', 'gel-filled'],
    colors: ['green', 'blue-green'],
    season: 'Year-round'
  },
  {
    id: 3,
    name: 'Anthurium',
    scientificName: 'Anthurium andraeanum',
    kaggleId: 'anthurium',
    family: 'Araceae',
    type: 'Flowering Houseplant',
    care: 'Moderate',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Tropical plant known for its glossy heart-shaped flowers in bright colors.',
    benefits: ['Long-lasting flowers', 'Air purification', 'Tropical beauty'],
    commonIssues: ['Root rot', 'Scale insects', 'Bacterial blight'],
    tips: ['High humidity', 'Warm temperatures', 'Regular misting'],
    features: ['heart-shaped flowers', 'glossy leaves', 'colorful bracts'],
    colors: ['red', 'pink', 'white', 'orange'],
    season: 'Year-round blooming'
  },
  {
    id: 4,
    name: 'Areca Palm',
    scientificName: 'Dypsis lutescens',
    kaggleId: 'areca_palm',
    family: 'Arecaceae',
    type: 'Palm Tree',
    care: 'Moderate',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Popular indoor palm with feathery, arching fronds and golden stems.',
    benefits: ['Air purification', 'Humidity regulation', 'Tropical ambiance'],
    commonIssues: ['Spider mites', 'Scale insects', 'Brown tips'],
    tips: ['Keep soil moist', 'High humidity', 'Regular misting'],
    features: ['feathery fronds', 'golden stems', 'arching growth'],
    colors: ['green', 'yellow'],
    season: 'Year-round'
  },
  {
    id: 5,
    name: 'Asparagus Fern',
    scientificName: 'Asparagus setaceus',
    kaggleId: 'asparagus_fern',
    family: 'Asparagaceae',
    type: 'Fern-like Plant',
    care: 'Moderate',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Delicate, feathery foliage plant that\'s not actually a true fern.',
    benefits: ['Delicate texture', 'Air purification', 'Cascading growth'],
    commonIssues: ['Yellow needles', 'Spider mites', 'Dropping foliage'],
    tips: ['Regular misting', 'Consistent moisture', 'Good air circulation'],
    features: ['needle-like leaves', 'feathery texture', 'climbing tendency'],
    colors: ['bright green'],
    season: 'Year-round'
  },
  {
    id: 6,
    name: 'Begonia',
    scientificName: 'Begonia species',
    kaggleId: 'begonia',
    family: 'Begoniaceae',
    type: 'Flowering Houseplant',
    care: 'Moderate',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Diverse group of plants with colorful flowers and attractive foliage.',
    benefits: ['Colorful flowers', 'Attractive foliage', 'Long blooming'],
    commonIssues: ['Powdery mildew', 'Root rot', 'Aphids'],
    tips: ['Good air circulation', 'Avoid overhead watering', 'Regular feeding'],
    features: ['asymmetrical leaves', 'colorful flowers', 'succulent stems'],
    colors: ['red', 'pink', 'white', 'orange', 'yellow'],
    season: 'Spring to Fall blooming'
  },
  {
    id: 7,
    name: 'Bird of Paradise',
    scientificName: 'Strelitzia reginae',
    kaggleId: 'bird_of_paradise',
    family: 'Strelitziaceae',
    type: 'Tropical Plant',
    care: 'Moderate',
    sunlight: 'Bright Direct',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Dramatic plant with large paddle-shaped leaves and exotic bird-like flowers.',
    benefits: ['Exotic flowers', 'Dramatic foliage', 'Statement plant'],
    commonIssues: ['Scale insects', 'Spider mites', 'Brown leaf edges'],
    tips: ['Bright light essential', 'Regular feeding', 'High humidity'],
    features: ['large paddle leaves', 'orange and blue flowers', 'tall growth'],
    colors: ['orange', 'blue', 'green'],
    season: 'Winter to Spring blooming'
  },
  {
    id: 8,
    name: 'Birds Nest Fern',
    scientificName: 'Asplenium nidus',
    kaggleId: 'birds_nest_fern',
    family: 'Aspleniaceae',
    type: 'Fern',
    care: 'Moderate',
    sunlight: 'Low to Medium',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Tropical fern with broad, wavy fronds arranged in a nest-like rosette.',
    benefits: ['Air purification', 'Low light tolerance', 'Unique texture'],
    commonIssues: ['Scale insects', 'Mealybugs', 'Brown frond tips'],
    tips: ['High humidity', 'Avoid touching new fronds', 'Consistent moisture'],
    features: ['broad wavy fronds', 'rosette pattern', 'glossy leaves'],
    colors: ['bright green'],
    season: 'Year-round'
  },
  {
    id: 9,
    name: 'Boston Fern',
    scientificName: 'Nephrolepis exaltata',
    kaggleId: 'boston_fern',
    family: 'Lomariopsidaceae',
    type: 'Fern',
    care: 'Moderate',
    sunlight: 'Bright Indirect',
    water: 'High',
    soil: 'Well-drained',
    description: 'Classic hanging fern with arching, feathery fronds.',
    benefits: ['Air purification', 'Humidity regulation', 'Classic beauty'],
    commonIssues: ['Brown fronds', 'Scale insects', 'Dropping leaflets'],
    tips: ['High humidity', 'Consistent moisture', 'Cool temperatures'],
    features: ['feathery fronds', 'arching growth', 'divided leaves'],
    colors: ['green'],
    season: 'Year-round'
  },
  {
    id: 10,
    name: 'Calathea',
    scientificName: 'Calathea species',
    kaggleId: 'calathea',
    family: 'Marantaceae',
    type: 'Foliage Plant',
    care: 'Difficult',
    sunlight: 'Low to Medium',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Prayer plant with beautiful patterned leaves that fold up at night.',
    benefits: ['Beautiful patterns', 'Air purification', 'Night movement'],
    commonIssues: ['Brown leaf edges', 'Spider mites', 'Leaf curling'],
    tips: ['High humidity', 'Filtered water', 'Consistent moisture'],
    features: ['patterned leaves', 'prayer movement', 'colorful undersides'],
    colors: ['green', 'purple', 'pink', 'white'],
    season: 'Year-round'
  },
  {
    id: 11,
    name: 'Chinese Evergreen',
    scientificName: 'Aglaonema species',
    kaggleId: 'chinese_evergreen',
    family: 'Araceae',
    type: 'Foliage Plant',
    care: 'Easy',
    sunlight: 'Low to Medium',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Colorful foliage plant with variegated leaves in various patterns.',
    benefits: ['Low light tolerance', 'Air purification', 'Colorful foliage'],
    commonIssues: ['Root rot', 'Scale insects', 'Bacterial leaf blight'],
    tips: ['Avoid cold drafts', 'Let soil dry between waterings', 'Warm temperatures'],
    features: ['variegated leaves', 'compact growth', 'colorful patterns'],
    colors: ['green', 'pink', 'red', 'silver'],
    season: 'Year-round'
  },
  {
    id: 12,
    name: 'Croton',
    scientificName: 'Codiaeum variegatum',
    kaggleId: 'croton',
    family: 'Euphorbiaceae',
    type: 'Foliage Plant',
    care: 'Moderate',
    sunlight: 'Bright Direct',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Tropical plant with brilliantly colored, thick, leathery leaves.',
    benefits: ['Colorful foliage', 'Air purification', 'Tropical beauty'],
    commonIssues: ['Scale insects', 'Mealybugs', 'Leaf drop'],
    tips: ['Bright light for color', 'High humidity', 'Consistent watering'],
    features: ['thick leathery leaves', 'brilliant colors', 'varied leaf shapes'],
    colors: ['red', 'orange', 'yellow', 'green', 'purple'],
    season: 'Year-round'
  },
  {
    id: 13,
    name: 'Dieffenbachia',
    scientificName: 'Dieffenbachia seguine',
    kaggleId: 'dieffenbachia',
    family: 'Araceae',
    type: 'Foliage Plant',
    care: 'Easy',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Large-leaved plant with attractive white and green variegation.',
    benefits: ['Air purification', 'Large dramatic leaves', 'Easy care'],
    commonIssues: ['Root rot', 'Scale insects', 'Bacterial leaf spot'],
    tips: ['Toxic if ingested', 'Rotate regularly', 'Clean leaves often'],
    features: ['large variegated leaves', 'thick stems', 'tropical appearance'],
    colors: ['green', 'white', 'cream'],
    season: 'Year-round'
  },
  {
    id: 14,
    name: 'Dracaena',
    scientificName: 'Dracaena fragrans',
    kaggleId: 'dracaena',
    family: 'Asparagaceae',
    type: 'Tree-like Plant',
    care: 'Easy',
    sunlight: 'Bright Indirect',
    water: 'Low to Moderate',
    soil: 'Well-drained',
    description: 'Tree-like plant with long, narrow leaves often with colorful stripes.',
    benefits: ['Air purification', 'Low maintenance', 'Architectural form'],
    commonIssues: ['Brown leaf tips', 'Scale insects', 'Root rot'],
    tips: ['Use filtered water', 'Let soil dry between waterings', 'Prune brown tips'],
    features: ['long narrow leaves', 'tree-like form', 'colorful stripes'],
    colors: ['green', 'yellow', 'red'],
    season: 'Year-round'
  },
  {
    id: 15,
    name: 'English Ivy',
    scientificName: 'Hedera helix',
    kaggleId: 'english_ivy',
    family: 'Araliaceae',
    type: 'Climbing Vine',
    care: 'Easy',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Classic climbing vine with lobed leaves, excellent for hanging baskets.',
    benefits: ['Air purification', 'Climbing ability', 'Classic beauty'],
    commonIssues: ['Spider mites', 'Scale insects', 'Aphids'],
    tips: ['Cool temperatures preferred', 'Good air circulation', 'Regular pruning'],
    features: ['lobed leaves', 'climbing vines', 'trailing growth'],
    colors: ['green', 'variegated'],
    season: 'Year-round'
  },
  {
    id: 16,
    name: 'Ficus',
    scientificName: 'Ficus benjamina',
    kaggleId: 'ficus',
    family: 'Moraceae',
    type: 'Tree',
    care: 'Moderate',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Popular indoor tree with small, glossy leaves and braided trunk options.',
    benefits: ['Air purification', 'Tree-like structure', 'Flexible styling'],
    commonIssues: ['Leaf drop', 'Scale insects', 'Thrips'],
    tips: ['Consistent conditions', 'Avoid moving frequently', 'Regular pruning'],
    features: ['small glossy leaves', 'tree structure', 'flexible branches'],
    colors: ['green', 'variegated'],
    season: 'Year-round'
  },
  {
    id: 17,
    name: 'Fiddle Leaf Fig',
    scientificName: 'Ficus lyrata',
    kaggleId: 'fiddle_leaf_fig',
    family: 'Moraceae',
    type: 'Tree',
    care: 'Difficult',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Trendy plant with large, violin-shaped leaves and tree-like growth.',
    benefits: ['Statement plant', 'Large dramatic leaves', 'Air purification'],
    commonIssues: ['Brown spots', 'Leaf drop', 'Root rot'],
    tips: ['Consistent watering', 'Bright indirect light', 'Avoid moving'],
    features: ['large violin-shaped leaves', 'tree form', 'prominent veining'],
    colors: ['dark green'],
    season: 'Year-round'
  },
  {
    id: 18,
    name: 'Haworthia',
    scientificName: 'Haworthia species',
    kaggleId: 'haworthia',
    family: 'Asphodelaceae',
    type: 'Succulent',
    care: 'Easy',
    sunlight: 'Bright Indirect',
    water: 'Low',
    soil: 'Sandy/Well-drained',
    description: 'Small succulent with thick, pointed leaves often with white markings.',
    benefits: ['Low maintenance', 'Compact size', 'Unique patterns'],
    commonIssues: ['Root rot', 'Overwatering', 'Mealybugs'],
    tips: ['Very little water', 'Bright but not direct sun', 'Good drainage'],
    features: ['thick pointed leaves', 'white markings', 'rosette form'],
    colors: ['green', 'white'],
    season: 'Year-round'
  },
  {
    id: 19,
    name: 'Jade Plant',
    scientificName: 'Crassula ovata',
    kaggleId: 'jade_plant',
    family: 'Crassulaceae',
    type: 'Succulent',
    care: 'Easy',
    sunlight: 'Bright Direct',
    water: 'Low',
    soil: 'Sandy/Well-drained',
    description: 'Popular succulent with thick, oval leaves and tree-like growth when mature.',
    benefits: ['Very low maintenance', 'Long-lived', 'Good luck symbol'],
    commonIssues: ['Root rot', 'Mealybugs', 'Overwatering'],
    tips: ['Let soil dry completely', 'Bright light essential', 'Prune for shape'],
    features: ['thick oval leaves', 'tree-like growth', 'glossy leaves'],
    colors: ['green', 'red edges'],
    season: 'Year-round'
  },
  {
    id: 20,
    name: 'Monstera',
    scientificName: 'Monstera deliciosa',
    kaggleId: 'monstera',
    family: 'Araceae',
    type: 'Tropical Houseplant',
    care: 'Moderate',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Popular houseplant known for its large, split leaves and climbing nature.',
    benefits: ['Air purification', 'Humidity regulation', 'Aesthetic appeal'],
    commonIssues: ['Yellow leaves', 'Root rot', 'Spider mites'],
    tips: ['Provide support for climbing', 'Mist regularly', 'Rotate for even growth'],
    features: ['split leaves', 'large holes', 'climbing vine', 'glossy green'],
    colors: ['green'],
    season: 'Year-round'
  },
  {
    id: 21,
    name: 'Norfolk Pine',
    scientificName: 'Araucaria heterophylla',
    kaggleId: 'norfolk_pine',
    family: 'Araucariaceae',
    type: 'Conifer Tree',
    care: 'Moderate',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Elegant indoor tree with symmetrical branching and soft, needle-like foliage.',
    benefits: ['Christmas tree alternative', 'Air purification', 'Unique texture'],
    commonIssues: ['Brown needles', 'Scale insects', 'Dry air damage'],
    tips: ['High humidity', 'Cool temperatures', 'Consistent moisture'],
    features: ['needle-like leaves', 'symmetrical branches', 'tree form'],
    colors: ['green'],
    season: 'Year-round'
  },
  {
    id: 22,
    name: 'Parlor Palm',
    scientificName: 'Chamaedorea elegans',
    kaggleId: 'parlor_palm',
    family: 'Arecaceae',
    type: 'Palm Tree',
    care: 'Easy',
    sunlight: 'Low to Medium',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Compact palm with delicate, feathery fronds, perfect for low light areas.',
    benefits: ['Low light tolerance', 'Air purification', 'Compact size'],
    commonIssues: ['Spider mites', 'Scale insects', 'Brown tips'],
    tips: ['High humidity', 'Avoid direct sun', 'Regular misting'],
    features: ['feathery fronds', 'compact size', 'delicate appearance'],
    colors: ['green'],
    season: 'Year-round'
  },
  {
    id: 23,
    name: 'Peace Lily',
    scientificName: 'Spathiphyllum wallisii',
    kaggleId: 'peace_lily',
    family: 'Araceae',
    type: 'Flowering Houseplant',
    care: 'Easy',
    sunlight: 'Low to Medium',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Elegant plant with dark green leaves and white flower spathes.',
    benefits: ['Air purification', 'Low light tolerance', 'Beautiful flowers'],
    commonIssues: ['Brown tips', 'Overwatering', 'Lack of humidity'],
    tips: ['Keep soil moist', 'Increase humidity', 'Remove dead flowers'],
    features: ['white flowers', 'dark green leaves', 'upright growth', 'lance-shaped leaves'],
    colors: ['white', 'green'],
    season: 'Year-round'
  },
  {
    id: 24,
    name: 'Philodendron',
    scientificName: 'Philodendron hederaceum',
    kaggleId: 'philodendron',
    family: 'Araceae',
    type: 'Climbing Vine',
    care: 'Easy',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Heart-shaped leaves on trailing or climbing vines, very easy to grow.',
    benefits: ['Air purification', 'Easy propagation', 'Fast growing'],
    commonIssues: ['Root rot', 'Aphids', 'Yellow leaves'],
    tips: ['Let soil dry between waterings', 'Provide support or let trail', 'Regular pruning'],
    features: ['heart-shaped leaves', 'trailing vines', 'glossy foliage'],
    colors: ['green', 'variegated'],
    season: 'Year-round'
  },
  {
    id: 25,
    name: 'Ponytail Palm',
    scientificName: 'Beaucarnea recurvata',
    kaggleId: 'ponytail_palm',
    family: 'Asparagaceae',
    type: 'Succulent Tree',
    care: 'Easy',
    sunlight: 'Bright Direct',
    water: 'Low',
    soil: 'Well-drained',
    description: 'Unique plant with a swollen trunk base and long, narrow, curly leaves.',
    benefits: ['Very low maintenance', 'Drought tolerant', 'Unique appearance'],
    commonIssues: ['Root rot', 'Scale insects', 'Overwatering'],
    tips: ['Water very infrequently', 'Bright light essential', 'Good drainage crucial'],
    features: ['swollen trunk base', 'long curly leaves', 'unique form'],
    colors: ['green'],
    season: 'Year-round'
  },
  {
    id: 26,
    name: 'Pothos',
    scientificName: 'Epipremnum aureum',
    kaggleId: 'pothos',
    family: 'Araceae',
    type: 'Climbing Vine',
    care: 'Very Easy',
    sunlight: 'Low to Bright',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Extremely popular trailing vine with heart-shaped, variegated leaves.',
    benefits: ['Air purification', 'Very easy care', 'Fast growing', 'Low light tolerance'],
    commonIssues: ['Root rot', 'Mealybugs', 'Overwatering'],
    tips: ['Let soil dry between waterings', 'Prune regularly', 'Easy to propagate'],
    features: ['heart-shaped leaves', 'trailing vines', 'variegated foliage'],
    colors: ['green', 'yellow', 'white'],
    season: 'Year-round'
  },
  {
    id: 27,
    name: 'Prayer Plant',
    scientificName: 'Maranta leuconeura',
    kaggleId: 'prayer_plant',
    family: 'Marantaceae',
    type: 'Foliage Plant',
    care: 'Moderate',
    sunlight: 'Low to Medium',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Beautiful plant with patterned leaves that fold up at night like praying hands.',
    benefits: ['Beautiful patterns', 'Night movement', 'Air purification'],
    commonIssues: ['Brown leaf edges', 'Spider mites', 'Leaf curling'],
    tips: ['High humidity', 'Filtered water', 'Avoid direct sunlight'],
    features: ['patterned leaves', 'prayer movement', 'red veining'],
    colors: ['green', 'red', 'cream'],
    season: 'Year-round'
  },
  {
    id: 28,
    name: 'Rubber Plant',
    scientificName: 'Ficus elastica',
    kaggleId: 'rubber_plant',
    family: 'Moraceae',
    type: 'Tree/Houseplant',
    care: 'Easy',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Popular houseplant with large, glossy, oval-shaped leaves.',
    benefits: ['Air purification', 'Easy care', 'Fast growing'],
    commonIssues: ['Leaf drop', 'Scale insects', 'Overwatering'],
    tips: ['Wipe leaves clean', 'Prune for shape', 'Consistent watering'],
    features: ['large oval leaves', 'glossy surface', 'thick trunk', 'dark green'],
    colors: ['green', 'burgundy'],
    season: 'Year-round'
  },
  {
    id: 29,
    name: 'Schefflera',
    scientificName: 'Schefflera actinophylla',
    kaggleId: 'schefflera',
    family: 'Araliaceae',
    type: 'Tree/Shrub',
    care: 'Easy',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Umbrella tree with distinctive palmate leaves arranged like umbrella spokes.',
    benefits: ['Air purification', 'Easy care', 'Fast growing'],
    commonIssues: ['Scale insects', 'Aphids', 'Leaf drop'],
    tips: ['Bright indirect light', 'Let soil dry between waterings', 'Regular pruning'],
    features: ['palmate leaves', 'umbrella shape', 'glossy foliage'],
    colors: ['green', 'variegated'],
    season: 'Year-round'
  },
  {
    id: 30,
    name: 'Snake Plant',
    scientificName: 'Sansevieria trifasciata',
    kaggleId: 'snake_plant',
    family: 'Asparagaceae',
    type: 'Succulent',
    care: 'Very Easy',
    sunlight: 'Low to Bright',
    water: 'Very Low',
    soil: 'Well-drained',
    description: 'Hardy indoor plant with tall, sword-like leaves featuring yellow edges.',
    benefits: ['Air purification', 'Low maintenance', 'Oxygen production at night'],
    commonIssues: ['Root rot', 'Overwatering', 'Scale insects'],
    tips: ['Water very sparingly', 'Tolerates neglect', 'Clean leaves regularly'],
    features: ['tall upright leaves', 'yellow edges', 'thick succulent leaves'],
    colors: ['green', 'yellow'],
    season: 'Year-round'
  },
  {
    id: 31,
    name: 'Spider Plant',
    scientificName: 'Chlorophytum comosum',
    kaggleId: 'spider_plant',
    family: 'Asparagaceae',
    type: 'Houseplant',
    care: 'Very Easy',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Easy-care plant with long, thin leaves and baby plantlets on runners.',
    benefits: ['Air purification', 'Pet-safe', 'Easy propagation'],
    commonIssues: ['Brown tips', 'Root bound', 'Low humidity'],
    tips: ['Propagate plantlets', 'Regular watering', 'Good drainage'],
    features: ['long thin leaves', 'white stripes', 'plantlets on runners'],
    colors: ['green', 'white'],
    season: 'Year-round'
  },
  {
    id: 32,
    name: 'Swiss Cheese Plant',
    scientificName: 'Monstera adansonii',
    kaggleId: 'swiss_cheese_plant',
    family: 'Araceae',
    type: 'Climbing Vine',
    care: 'Moderate',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Climbing plant with distinctive holes in the leaves, smaller than Monstera deliciosa.',
    benefits: ['Air purification', 'Unique leaf pattern', 'Climbing ability'],
    commonIssues: ['Yellow leaves', 'Root rot', 'Spider mites'],
    tips: ['Provide support for climbing', 'High humidity', 'Regular pruning'],
    features: ['holes in leaves', 'climbing vines', 'heart-shaped leaves'],
    colors: ['green'],
    season: 'Year-round'
  },
  {
    id: 33,
    name: 'ZZ Plant',
    scientificName: 'Zamioculcas zamiifolia',
    kaggleId: 'zz_plant',
    family: 'Araceae',
    type: 'Succulent-like',
    care: 'Very Easy',
    sunlight: 'Low to Bright',
    water: 'Very Low',
    soil: 'Well-drained',
    description: 'Extremely low-maintenance plant with glossy, waxy leaves on upright stems.',
    benefits: ['Very low maintenance', 'Low light tolerance', 'Air purification'],
    commonIssues: ['Root rot', 'Overwatering', 'Scale insects'],
    tips: ['Water very infrequently', 'Tolerates low light', 'Clean leaves regularly'],
    features: ['glossy waxy leaves', 'upright stems', 'thick rhizomes'],
    colors: ['dark green'],
    season: 'Year-round'
  },
  {
    id: 34,
    name: 'Yucca',
    scientificName: 'Yucca elephantipes',
    kaggleId: 'yucca',
    family: 'Asparagaceae',
    type: 'Tree/Succulent',
    care: 'Easy',
    sunlight: 'Bright Direct',
    water: 'Low',
    soil: 'Sandy/Well-drained',
    description: 'Desert plant with sword-like leaves and thick trunk, very drought tolerant.',
    benefits: ['Very drought tolerant', 'Architectural form', 'Low maintenance'],
    commonIssues: ['Root rot', 'Scale insects', 'Overwatering'],
    tips: ['Bright light essential', 'Water very sparingly', 'Good drainage crucial'],
    features: ['sword-like leaves', 'thick trunk', 'sharp leaf tips'],
    colors: ['green'],
    season: 'Year-round'
  },
  {
    id: 35,
    name: 'Weeping Fig',
    scientificName: 'Ficus benjamina',
    kaggleId: 'weeping_fig',
    family: 'Moraceae',
    type: 'Tree',
    care: 'Moderate',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Graceful indoor tree with small, glossy leaves and drooping branches.',
    benefits: ['Air purification', 'Tree-like structure', 'Elegant appearance'],
    commonIssues: ['Leaf drop', 'Scale insects', 'Thrips'],
    tips: ['Consistent conditions', 'Avoid moving frequently', 'Regular pruning'],
    features: ['small glossy leaves', 'drooping branches', 'tree structure'],
    colors: ['green', 'variegated'],
    season: 'Year-round'
  },
  {
    id: 36,
    name: 'Wandering Jew',
    scientificName: 'Tradescantia zebrina',
    kaggleId: 'wandering_jew',
    family: 'Commelinaceae',
    type: 'Trailing Plant',
    care: 'Easy',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Fast-growing trailing plant with purple and silver striped leaves.',
    benefits: ['Fast growing', 'Easy propagation', 'Colorful foliage'],
    commonIssues: ['Leggy growth', 'Aphids', 'Root rot'],
    tips: ['Pinch regularly for fullness', 'Easy to propagate', 'Bright light for color'],
    features: ['striped leaves', 'trailing growth', 'purple undersides'],
    colors: ['green', 'purple', 'silver'],
    season: 'Year-round'
  },
  {
    id: 37,
    name: 'Venus Flytrap',
    scientificName: 'Dionaea muscipula',
    kaggleId: 'venus_flytrap',
    family: 'Droseraceae',
    type: 'Carnivorous Plant',
    care: 'Difficult',
    sunlight: 'Bright Direct',
    water: 'High',
    soil: 'Acidic/Sphagnum',
    description: 'Fascinating carnivorous plant with snap traps that catch and digest insects.',
    benefits: ['Natural pest control', 'Educational value', 'Unique appearance'],
    commonIssues: ['Dormancy needs', 'Water quality', 'Humidity requirements'],
    tips: ['Use distilled water only', 'Need winter dormancy', 'High humidity essential'],
    features: ['snap traps', 'trigger hairs', 'carnivorous nature'],
    colors: ['green', 'red'],
    season: 'Spring to Fall active'
  },
  {
    id: 38,
    name: 'Umbrella Tree',
    scientificName: 'Schefflera arboricola',
    kaggleId: 'umbrella_tree',
    family: 'Araliaceae',
    type: 'Tree/Shrub',
    care: 'Easy',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Compact version of Schefflera with small, glossy leaflets arranged like umbrella spokes.',
    benefits: ['Air purification', 'Compact size', 'Easy care'],
    commonIssues: ['Scale insects', 'Aphids', 'Overwatering'],
    tips: ['Bright indirect light', 'Let soil dry between waterings', 'Pinch for bushiness'],
    features: ['small glossy leaflets', 'umbrella arrangement', 'compact growth'],
    colors: ['green', 'variegated'],
    season: 'Year-round'
  },
  {
    id: 39,
    name: 'Ti Plant',
    scientificName: 'Cordyline fruticosa',
    kaggleId: 'ti_plant',
    family: 'Asparagaceae',
    type: 'Tropical Plant',
    care: 'Moderate',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Tropical plant with colorful, lance-shaped leaves in various colors.',
    benefits: ['Colorful foliage', 'Tropical appearance', 'Air purification'],
    commonIssues: ['Brown leaf tips', 'Scale insects', 'Low humidity'],
    tips: ['High humidity', 'Bright light for color', 'Regular misting'],
    features: ['lance-shaped leaves', 'colorful foliage', 'tropical appearance'],
    colors: ['red', 'pink', 'green', 'yellow'],
    season: 'Year-round'
  },
  {
    id: 40,
    name: 'Thanksgiving Cactus',
    scientificName: 'Schlumbergera truncata',
    kaggleId: 'thanksgiving_cactus',
    family: 'Cactaceae',
    type: 'Epiphytic Cactus',
    care: 'Moderate',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Holiday cactus with segmented stems and colorful flowers in fall.',
    benefits: ['Holiday blooms', 'Easy care', 'Long-lived'],
    commonIssues: ['Bud drop', 'Root rot', 'Scale insects'],
    tips: ['Cool temperatures for blooming', 'Short day length needed', 'Well-draining soil'],
    features: ['segmented stems', 'colorful flowers', 'succulent nature'],
    colors: ['pink', 'red', 'white', 'orange'],
    season: 'Fall blooming'
  },
  {
    id: 41,
    name: 'String of Pearls',
    scientificName: 'Senecio rowleyanus',
    kaggleId: 'string_of_pearls',
    family: 'Asteraceae',
    type: 'Succulent',
    care: 'Moderate',
    sunlight: 'Bright Indirect',
    water: 'Low',
    soil: 'Well-drained',
    description: 'Unique trailing succulent with bead-like leaves on long stems.',
    benefits: ['Unique appearance', 'Trailing growth', 'Low water needs'],
    commonIssues: ['Overwatering', 'Root rot', 'Aphids'],
    tips: ['Water sparingly', 'Good drainage essential', 'Bright indirect light'],
    features: ['bead-like leaves', 'trailing stems', 'succulent nature'],
    colors: ['green'],
    season: 'Year-round'
  },
  {
    id: 42,
    name: 'String of Hearts',
    scientificName: 'Ceropegia woodii',
    kaggleId: 'string_of_hearts',
    family: 'Apocynaceae',
    type: 'Succulent Vine',
    care: 'Easy',
    sunlight: 'Bright Indirect',
    water: 'Low',
    soil: 'Well-drained',
    description: 'Charming trailing succulent with heart-shaped leaves and purple undersides.',
    benefits: ['Unique heart-shaped leaves', 'Trailing growth', 'Easy propagation'],
    commonIssues: ['Overwatering', 'Aphids', 'Root rot'],
    tips: ['Water sparingly', 'Bright light for variegation', 'Easy to propagate'],
    features: ['heart-shaped leaves', 'trailing vines', 'purple undersides'],
    colors: ['green', 'silver', 'purple'],
    season: 'Year-round'
  },
  {
    id: 43,
    name: 'Staghorn Fern',
    scientificName: 'Platycerium bifurcatum',
    kaggleId: 'staghorn_fern',
    family: 'Polypodiaceae',
    type: 'Epiphytic Fern',
    care: 'Moderate',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Mounted/Well-drained',
    description: 'Unique mounted fern with antler-shaped fronds, grows naturally on trees.',
    benefits: ['Unique mounting option', 'Air plant qualities', 'Conversation piece'],
    commonIssues: ['Overwatering', 'Low humidity', 'Scale insects'],
    tips: ['Mount on wood or bark', 'Soak watering method', 'High humidity'],
    features: ['antler-shaped fronds', 'epiphytic growth', 'mounted display'],
    colors: ['green'],
    season: 'Year-round'
  },
  {
    id: 44,
    name: 'Sago Palm',
    scientificName: 'Cycas revoluta',
    kaggleId: 'sago_palm',
    family: 'Cycadaceae',
    type: 'Cycad',
    care: 'Moderate',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Ancient plant with feathery fronds arranged in a crown, slow-growing.',
    benefits: ['Ancient appearance', 'Architectural form', 'Long-lived'],
    commonIssues: ['Scale insects', 'Root rot', 'Yellow fronds'],
    tips: ['Very slow growing', 'Well-draining soil', 'Bright indirect light'],
    features: ['feathery fronds', 'crown arrangement', 'thick trunk'],
    colors: ['dark green'],
    season: 'Year-round'
  },
  {
    id: 45,
    name: 'Rosemary',
    scientificName: 'Rosmarinus officinalis',
    kaggleId: 'rosemary',
    family: 'Lamiaceae',
    type: 'Herb',
    care: 'Moderate',
    sunlight: 'Bright Direct',
    water: 'Low to Moderate',
    soil: 'Well-drained',
    description: 'Aromatic herb with needle-like leaves, can be grown indoors with bright light.',
    benefits: ['Culinary use', 'Aromatic foliage', 'Natural pest deterrent'],
    commonIssues: ['Powdery mildew', 'Root rot', 'Aphids'],
    tips: ['Bright light essential', 'Good air circulation', 'Harvest regularly'],
    features: ['needle-like leaves', 'aromatic', 'woody stems'],
    colors: ['green'],
    season: 'Year-round'
  },
  {
    id: 46,
    name: 'Polka Dot Plant',
    scientificName: 'Hypoestes phyllostachya',
    kaggleId: 'polka_dot_plant',
    family: 'Acanthaceae',
    type: 'Foliage Plant',
    care: 'Moderate',
    sunlight: 'Bright Indirect',
    water: 'Moderate',
    soil: 'Well-drained',
    description: 'Colorful plant with spotted leaves in various color combinations.',
    benefits: ['Colorful foliage', 'Compact size', 'Easy propagation'],
    commonIssues: ['Leggy growth', 'Aphids', 'Powdery mildew'],
    tips: ['Pinch flowers', 'Bright light for color', 'Regular pinching for bushiness'],
    features: ['spotted leaves', 'colorful patterns', 'soft texture'],
    colors: ['pink', 'red', 'white', 'green'],
    season: 'Year-round'
  },
  {
    id: 47,
    name: 'Peperomia',
    scientificName: 'Peperomia obtusifolia',
    kaggleId: 'peperomia',
    family: 'Piperaceae',
    type: 'Foliage Plant',
    care: 'Easy',
    sunlight: 'Bright Indirect',
    water: 'Low to Moderate',
    soil: 'Well-drained',
    description: 'Compact plant with thick, waxy leaves in various shapes and colors.',
    benefits: ['Compact size', 'Low maintenance', 'Variety of forms'],
    commonIssues: ['Root rot', 'Mealybugs', 'Overwatering'],
    tips: ['Let soil dry between waterings', 'Bright indirect light', 'Good drainage'],
    features: ['thick waxy leaves', 'compact growth', 'varied leaf shapes'],
    colors: ['green', 'variegated', 'red'],
    season: 'Year-round'
  }
];